[book]
authors = ["tasuren"]
language = "ja"
multilingual = false
src = "src"
title = "libtsrn"

[output.html]
git-repository-url = "https://github.com/libtsrn/home"
edit-url-template = "https://github.com/libtsrn/home/edit/main/{path}"